# -- DATA MANIPULATION WITH PYTHON 

## * Numpy

In [2]:
import numpy as np 

In [5]:
a=np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [6]:
print("Array Shape: "+ (str)(a.shape))
print("Array Number of axes: "+ (str)(a.ndim))
print("Array Data Type: "+ (str)(a.dtype))
print("Array Item Size Byte: "+ (str)(a.itemsize))
print("Array Number of All Elements: "+ (str)(a.size))
print("Data Type: "+ (str)(type(a)))


Array Shape: (3, 5)
Array Number of axes: 2
Array Data Type: int32
Array Item Size Byte: 4
Array Number of All Elements: 15
Data Type: <class 'numpy.ndarray'>


### //Array creation with numpy

In [12]:
b=np.array([(1,2,3),(4,5,6)],dtype=complex)
b

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j]])

In [23]:
np.zeros((3,4),dtype=np.int16)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int16)

In [22]:
np.ones((2,5),dtype=np.int16)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int16)

In [21]:
np.empty((2,3)) ##  initial content is random and depends on the state of the memory

array([[0., 0., 0.],
       [0., 0., 0.]])

In [26]:
np.arange(0.0,10.0,1.5) ##initial-final-coefficient

array([0. , 1.5, 3. , 4.5, 6. , 7.5, 9. ])

In [29]:
np.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [41]:
from numpy import pi
x = np.linspace( 0, 2*pi, 10 )
np.sin(x)

array([ 0.00000000e+00,  6.42787610e-01,  9.84807753e-01,  8.66025404e-01,
        3.42020143e-01, -3.42020143e-01, -8.66025404e-01, -9.84807753e-01,
       -6.42787610e-01, -2.44929360e-16])

### //Basic Operators

In [35]:
a*3

array([[ 0,  3,  6,  9, 12],
       [15, 18, 21, 24, 27],
       [30, 33, 36, 39, 42]])

In [39]:
a**a

array([[          1,           1,           4,          27,         256],
       [       3125,       46656,      823543,    16777216,   387420489],
       [ 1410065408,  1843829075,  -251658240, -1692154371, -1282129920]],
      dtype=int32)

In [40]:
a[2:5] # element index 2 to 5 print

array([[10, 11, 12, 13, 14]])

In [44]:
for i in a:
    print (i+5)

[5 6 7 8 9]
[10 11 12 13 14]
[15 16 17 18 19]


In [47]:
def f(x,y):
    return 10*x+y
functionArray=np.fromfunction(f,(2,2),dtype=int)
functionArray

array([[ 0,  1],
       [10, 11]])

### //Shaping

In [12]:
c=np.arange(0,15,2)
c.reshape(4,2).T #transposed

array([[ 0,  4,  8, 12],
       [ 2,  6, 10, 14]])

In [22]:
d=np.floor(10*np.random.random((2,6)))
d

array([[5., 0., 1., 1., 8., 1.],
       [5., 3., 6., 0., 7., 5.]])

In [24]:
np.hsplit(d,3)

[array([[5., 0.],
        [5., 3.]]),
 array([[1., 1.],
        [6., 0.]]),
 array([[8., 1.],
        [7., 5.]])]

In [25]:
e=d.copy()
e

array([[5., 0., 1., 1., 8., 1.],
       [5., 3., 6., 0., 7., 5.]])

In [27]:
e is d #complete copy (deep)

False

## ----------------------------------------------------------------------------------------------

## *PANDAS

In [29]:
import numpy as np
import pandas as pd

In [31]:
s=pd.Series([1,2,3,4,np.nan,6])
s

0    1.0
1    2.0
2    3.0
3    4.0
4    NaN
5    6.0
dtype: float64

In [32]:
s.axes

[RangeIndex(start=0, stop=6, step=1)]

In [33]:
s.dtype

dtype('float64')

In [34]:
s.size

6

In [35]:
s.ndim

1

In [36]:
s.values

array([ 1.,  2.,  3.,  4., nan,  6.])

In [37]:
s.head(3)

0    1.0
1    2.0
2    3.0
dtype: float64

In [38]:
s.tail(3)

3    4.0
4    NaN
5    6.0
dtype: float64

In [43]:
seri=pd.Series([1,2,3],index=['a','b','c'])

In [45]:
seri['b']

2

In [47]:
pd.concat([seri,seri])

a    1
b    2
c    3
a    1
b    2
c    3
dtype: int64

In [49]:
'a' in seri

True

### //Data Frames

In [51]:
ilist=[1,2,3,4]
a=pd.DataFrame(ilist,columns=['numbers'])
a

numbers
0        1
1        2
2        3
3        4

In [52]:
a.columns

Index(['numbers'], dtype='object')

In [53]:
a.values

array([[1],
       [2],
       [3],
       [4]], dtype=int64)

In [54]:
a.loc[0:3]

numbers
0        1
1        2
2        3
3        4

In [55]:
a.iloc[0:3]

numbers
0        1
1        2
2        3

In [57]:
import seaborn as sea #ready data sets
df=sea.load_dataset("planets")
df

method  number  orbital_period   mass  distance  year
0     Radial Velocity       1      269.300000   7.10     77.40  2006
1     Radial Velocity       1      874.774000   2.21     56.95  2008
2     Radial Velocity       1      763.000000   2.60     19.84  2011
3     Radial Velocity       1      326.030000  19.40    110.62  2007
4     Radial Velocity       1      516.220000  10.50    119.47  2009
...               ...     ...             ...    ...       ...   ...
1030          Transit       1        3.941507    NaN    172.00  2006
1031          Transit       1        2.615864    NaN    148.00  2007
1032          Transit       1        3.191524    NaN    174.00  2007
1033          Transit       1        4.125083    NaN    293.00  2008
1034          Transit       1        4.187757    NaN    260.00  2008

[1035 rows x 6 columns]

In [58]:
df.mean()

number               1.785507
orbital_period    2002.917596
mass                 2.638161
distance           264.069282
year              2009.070531
dtype: float64

In [59]:
df['mass'].mean()

2.6381605847953233

In [60]:
df.describe().T

count         mean           std          min         25%  \
number          1035.0     1.785507      1.240976     1.000000     1.00000   
orbital_period   992.0  2002.917596  26014.728304     0.090706     5.44254   
mass             513.0     2.638161      3.818617     0.003600     0.22900   
distance         808.0   264.069282    733.116493     1.350000    32.56000   
year            1035.0  2009.070531      3.972567  1989.000000  2007.00000   

                      50%       75%       max  
number             1.0000     2.000       7.0  
orbital_period    39.9795   526.005  730000.0  
mass               1.2600     3.040      25.0  
distance          55.2500   178.500    8500.0  
year            2010.0000  2012.000    2014.0

In [62]:
df.groupby('method').mean()

number  orbital_period      mass  \
method                                                              
Astrometry                     1.000000      631.180000       NaN   
Eclipse Timing Variations      1.666667     4751.644444  5.125000   
Imaging                        1.315789   118247.737500       NaN   
Microlensing                   1.173913     3153.571429       NaN   
Orbital Brightness Modulation  1.666667        0.709307       NaN   
Pulsar Timing                  2.200000     7343.021201       NaN   
Pulsation Timing Variations    1.000000     1170.000000       NaN   
Radial Velocity                1.721519      823.354680  2.630699   
Transit                        1.954660       21.102073  1.470000   
Transit Timing Variations      2.250000       79.783500       NaN   

                                  distance         year  
method                                                   
Astrometry                       17.875000  2011.500000  
Eclipse Timing Variations       315.360000  2010.000000  
Imaging                          67.715937  2009.131579  
Microlensing                   4144.000000  2009.782609  
Orbital Brightness Modulation  1180.000000  2011.666667  
Pulsar Timing                  1200.000000  1998.400000  
Pulsation Timing Variations            NaN  2007.000000  
Radial Velocity                  51.600208  2007.518987  
Transit                         599.298080  2011.236776  
Transit Timing Variations      1104.333333  2012.500000

In [64]:
df.groupby('method').aggregate(['min',np.median,'max'])

number            orbital_period                \
                                 min median max            min        median   
method                                                                         
Astrometry                         1      1   1     246.360000    631.180000   
Eclipse Timing Variations          1      2   2    1916.250000   4343.500000   
Imaging                            1      1   4    4639.150000  27500.000000   
Microlensing                       1      1   2    1825.000000   3300.000000   
Orbital Brightness Modulation      1      2   2       0.240104      0.342887   
Pulsar Timing                      1      3   3       0.090706     66.541900   
Pulsation Timing Variations        1      1   1    1170.000000   1170.000000   
Radial Velocity                    1      1   6       0.736540    360.200000   
Transit                            1      1   7       0.355000      5.714932   
Transit Timing Variations          2      2   3      22.339500     57.011000   

                                                mass               distance  \
                                         max     min median    max      min   
method                                                                        
Astrometry                       1016.000000     NaN    NaN    NaN    14.98   
Eclipse Timing Variations       10220.000000  4.2000  5.125   6.05   130.72   
Imaging                        730000.000000     NaN    NaN    NaN     7.69   
Microlensing                     5100.000000     NaN    NaN    NaN  1760.00   
Orbital Brightness Modulation       1.544929     NaN    NaN    NaN  1180.00   
Pulsar Timing                   36525.000000     NaN    NaN    NaN  1200.00   
Pulsation Timing Variations      1170.000000     NaN    NaN    NaN      NaN   
Radial Velocity                 17337.500000  0.0036  1.260  25.00     1.35   
Transit                           331.600590  1.4700  1.470   1.47    38.00   
Transit Timing Variations         160.000000     NaN    NaN    NaN   339.00   

                                                  year                
                                 median      max   min  median   max  
method                                                                
Astrometry                       17.875    20.77  2010  2011.5  2013  
Eclipse Timing Variations       315.360   500.00  2008  2010.0  2012  
Imaging                          40.395   165.00  2004  2009.0  2013  
Microlensing                   3840.000  7720.00  2004  2010.0  2013  
Orbital Brightness Modulation  1180.000  1180.00  2011  2011.0  2013  
Pulsar Timing                  1200.000  1200.00  1992  1994.0  2011  
Pulsation Timing Variations         NaN      NaN  2007  2007.0  2007  
Radial Velocity                  40.445   354.00  1989  2009.0  2014  
Transit                         341.000  8500.00  2002  2012.0  2014  
Transit Timing Variations       855.000  2119.00  2011  2012.5  2014